  name: PluginBuddies
  main: de.pluginbuddies.wintervillage.Main.Main
  version: 2.0
  api-version: 1.16

  commands:
    gm:
      description: Aendert deinen Spielmodus!
      aliases:
        - gamemode
    village:
      description: Teleportiert dich zu deinem Village!
    spawn:
      description: Teleportiert dich zum Spawn!
    prison:
      description: Sperrt einen Mitbuerger ins Gefaengnis!
    adventskalender:
      description: Oeffne dein taegliches Adventstuerchen!
      aliases:
        - advent
    vote:
      description: Waehle einen Buergermeister fuer dein Village!
    meet:
      description: Teleportiert alle Village-Bewohner zum Mittelpunkt des Villages für eine Besprechung.
    bp:
      description: Oeffnet dein Team-Backpack.
      aliases:
        - backpack
    confi:
      description: Startet eine Serverkonferent, sofern der andere Bürgermeister aktzeptiert!
    putsch:
      description: Erlaubt es dir, wenn weitere fuenf Mitbuerger aus deinem Dorf abstimmen, einen Putsch zu starten und deinen Buergermeister abzuwaehlen!
    clash:
      description: Oeffnet dir die Clash-Uebersicht!
    pos:
      description: Laesst dich Positionen speichern und lesen!
    wintervillagestart:
      description: only sys-admins

