  name: PluginBuddies
  main: de.pluginbuddies.wintervillage.Main.Main
  version: 1.0

  commands:
    gm:
      description: Aendert deinen Spielmodus!
    adventskalender:
      description: Oeffne dein taegliches Adventstuerchen.
      aliases:
        - advent