  name: PluginBuddies
  main: de.pluginbuddies.wintervillage.Main.Main
  version: 1.0

  commands:
    gm:
      description: Aendert deinen Spielmodus!
      aliases:
        - gamemode
    village:
      description: Teleportiert dich zu deinem Village!
    spawn:
      description: Teleportiert dich zum Spawn!
    prison:
      description: Sperrt einen Mitbuerger ins Gefaengnis!
    adventskalender:
      description: Oeffne dein taegliches Adventstuerchen!
      aliases:
        - advent
    vote:
      description: Waehle einen Buergermeister fuer dein Village!
    meet:
      description: Teleportiert alle Village-Bewohner zum Mittelpunkt des Villages für eine Besprechung.
    bp:
      description: Oeffnet dein Team-Backpack.
      aliases:
        - backpack