  name: PluginBuddies
  main: de.pluginbuddies.wintervillage.Main.Main
  version: 1.0

  commands:
    gm:
      description: Aendert deinen Spielmodus!
    village:
      description: Teleportiert dich zu deinem Village!
    spawn:
      description: Teleportiert dich zum Spawn
    prison:
      description: Sperrt einen Mitbuerger ins Gefaengnis!